# Generated by Django 3.1 on 2020-09-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fajr', models.TimeField()),
                ('Shorouk', models.TimeField()),
                ('Duhr', models.TimeField()),
                ('Asr', models.TimeField()),
                ('Maghrib', models.TimeField()),
                ('Aicha', models.TimeField()),
            ],
        ),
    ]
